### ISSUE TITLE
Question: bootstrapping compiler?

### ISSUE THREAD

**Issue by eudoxia0** [StanzaOrg/lbstanza-old#24]
I notice the source includes a compiled binary of the Stanza compiler, but no source code. I wanted to ask a few questions: 
- What is the bootstrapping compiler/interpreter written in?
- Do you compile to a relatively high-level language rather than machine code for bootstrapping?
- And, if so, do you defer type/error checking to that language? Or is it an "assume the compiler is correct, then the generated source will be correct" approach?

Thanks!

**Comment by MadcapJake** [comment]
Isn't the compiler in the `compiler/` folder?

**Comment by eudoxia0** [comment]
That's the source  of the compiler in Stanza, there's a bootstrapping compiler _somewhere_ written in  an existing language that turns that source into an executable.

**Comment by CuppoJava** [comment]
There was an old bootstrapping compiler written in Gambit Scheme that can compile a very early version of the Stanza language. But Stanza has been self-hosted for nearly three years now, and the language itself has changed a lot since then. The latest version of the language can only be compiled (or cross-compiled) with the self-hosted compiler now (which is in the compiler folder).

We compile to a high-level internal IR, which we then lower gradually to x86 ourselves.

There are a few global sanity and consistency checks in place that verify the well-formedness of the high-level internal IR. But it's not as full featured as a full type checker. So it's definitely currently leaning more towards the "assume the compiler is correct" approach.

**Comment by eudoxia0** [comment]
Ah, I see. So effectively there's a chain of bootstrapping compilers, starting with Scheme, and working up through the various versions of the Stanza compiler.

Have you thought about uploading the Scheme compiler, and the necessary copies of the compiler at different points in the Git history to compile the whole thing, from scratch?

**Comment by CuppoJava** [comment]
The bootstrapping process is not nearly as clean as they depict it in the textbooks. During early stage bootstrapping, small errors often result in corrupted binaries. And we sometimes had to go and apply binary patches to fix the compiled compilers in order to compile the next language version. 

We've thought that it would be nice to clean up the old compiler and present a sanitized sequential series of steps for building Stanza from nothing. But it's just not that high up on the list of priorities currently.
