### ISSUE TITLE
Generic way of defining functions doesn't work

### ISSUE THREAD

**Issue by porky11** [StanzaOrg/lbstanza-old#26]
example:

```
defn double<?T> (x:T):
  x + x
println(double(1))
```

says that there is no function plus for arguments of type (T, T)

**Comment by CuppoJava** [comment]
The error message is saying that there is no function called `plus` that is guaranteed to be able to work on `T`. This make sense since `T` can be anything.

```
double("Hello")
```

For example, the above call is nonsense. If you're _absolutely_ sure that this is something you want to do, you may explicitly cast it yourself.

```
defn double<?T> (x:?T) : 
   val x* = x as ?
   (x* + x*) as T
```

And Stanza will crash at runtime if you call `double` with inappropriate arguments.

**Comment by porky11** [comment]
I thought it would work like c++ templates
This way it also won't be compiled to efficient code

Following would also work secure, but then it would be nice to have some Number-Type so I won't have to write all types myself, and it would also work, if I define new Number-Types without redefining it

```
defn double<?T> (x:?T&(Byte|Int|Long|Float|Double)):
      val x* = x as ?
      x* + x* as T

```

(Defining such a Number-Type myself like `deftype Number <: (Byte|Int|Long|Float|Double)` may also be nice)
