### ISSUE TITLE
for with too many arguments

### ISSUE THREAD

**Issue by porky11** [StanzaOrg/lbstanza-old#27]
For doesn't work, when using too many arguments

```
for (x in xs y in ys) f :
  …
```

Wouldn't it be better if this construct would macro-expand into something like `f(fn(x y) : (…) [xs ys])` instead of `f(fn(x y) : (…) xs ys)`?
(a second for-like macro for this would also be ok)
Then one would be able to define functions that work for all number of arguments and specialized versions of the functions could be defined anyway (instead of `defn f (fun:(A B) -> C a:Seq<A> b:Seq<B>) -> Seq<C>` the functions could be defined `defn f (fun:(A B) -> C ab:[Seq<A> Seq<B>]) -> Seq<C>`)

**Comment by CuppoJava** [comment]
Can you give a concrete example of what you want to do and where the existing `for` macro is falling short? The `for` macro expansion is explicitly designed to allow for multiple collections.

**Comment by porky11** [comment]
some simple example would be this:

```
for (x in [1] y in [2] z in [3] w in [4]) do:
  println([x y z w]) ;should print [1 2 3 4]
```

or something useful: addition of seqables:

```
println(
  for (x in to-array<Int>([1 2 3]) y in to-array<Int>([4 5 6])) map:
    x + y
) ;should print [5 7 9]
```

**Comment by CuppoJava** [comment]
Okay. I understand your problem now. It's not a problem with the expansion of `for` though. It's caused by how the `do` and `map` functions are defined. The `do` operating function takes maximum only 3 collections. I can write another overloaded version that takes 4 collections. But ultimately there _will_ be some upper limit. Stanza doesn't support variable arity functions. 

Your `map` example on arrays is similarly limited because there just isn't a `map` function that takes in multiple arrays. It's not a solution to the need for variable-arity functions, but here's how your `map` example could be written:

```
val zs = to-array<Int> $
  for (x in [1 2 3], y in [4 5 6]) seq : 
    x + y
println(zs)
```

**Comment by porky11** [comment]
Yes, the problems is that these functions take a maximum number of arguments, so I think, it would be better for functions, that should take an arbitrary number of arguments, to define them to take a Seqable and for specialized versions to define them with tuple-types instead of multiple arguments.
For would then also have to expand differently then. (as described in the first post)

**Comment by CuppoJava** [comment]
Unfortunately, wrapping up the arguments in tuples doesn't fix the problem because the types of each argument cannot be calculated properly. Once we add support for variable-arity functions this limitation will go away. In the meantime, `zip-all` offers a very readable workaround:

```
for [x, y, z, w] in zip-all([1], [2], [3], [4]) do :
  println([x y z w]) ;should print [1 2 3 4]
```

**Comment by porky11** [comment]
Ok I didn't know, variable-arity-functions are planned, then there is no problem
